apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: team-portfolio
  name: team-portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team-portfolio
  strategy: {}
  template:
    metadata:
      labels:
        app: team-portfolio
    spec:
      containers:
        - image: IMAGE:TAG
          name: team-portfolio
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
status: {}
