apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: team-portfolio
  labels:
    name: team-portfolio
spec:
  ingressClassName: "nginx"
  rules:
    - http:
        paths:
          - path: /team-portfolio
            pathType: Prefix
            backend:
              service:
                name: team-portfolio
                port:
                  number: 80