name: Build and Deploy to GKE

on:
  push:
    branches: [ "develop" ]
  workflow_dispatch:

env:
  IMAGE: team-portfolio

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Configure Workload Identity Federation and generate an access token.
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
         credentials_json: ${{ secrets.SA_DEV_JSON }}
        
    - name: Docker configuration
      run: |-
       echo ${{ secrets.SA_DEV_JSON_BASE64 }} | docker login -u _json_key_base64 --password-stdin ${{ vars.GCR_REGISTRY }}
    # Get the GKE credentials so we can deploy to the cluster
    - name: Set up GKE credentials
      uses: google-github-actions/get-gke-credentials@v0
      with:
        cluster_name: ${{ vars.GKE_SB_CLUSTER }}
        location: ${{ vars.GKE_SB_REGION }}

    # Build the Docker image
    - name: Build
      run: |-
        docker build \
          --tag "${{ vars.GCR_REPOSITORY }}/$IMAGE:$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          .
    # Push the Docker image to Google Artifact Registry
    - name: Publish
      run: |-
        docker push "${{ vars.GCR_REPOSITORY }}/$IMAGE:$GITHUB_SHA"
    # Set up kustomize
    - name: Set up Kustomize
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize
    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |-
        # replacing the image name in the k8s template
        cd k8s/base
        ../../kustomize edit set image IMAGE:TAG=${{ vars.GCR_REPOSITORY }}/$IMAGE:$GITHUB_SHA
        ../../kustomize build . | kubectl apply -f -
